name: PR Review
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  data-review:
    uses: linz/topographic-system/.github/workflows/data-review.yml@feat/kart-stac-push
    with:
      environment: nonprod
      changed_datasets_only: false
      output: s3://linz-topography-nonprod/
      kart_version: pr-120
      strategy: ${{ (github.ref == 'refs/heads/master' && github.event_name == 'push') && format('latest,date,commit={0}', github.sha) || format('commit={0}', github.sha) }}
    secrets: inherit
