name: PR Review
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  data-review:
    uses: linz/topographic-system/.github/workflows/data-review.yml@master
    with:
      environment: nonprod
      changed_datasets_only: false
      output: s3://linz-topography-nonprod/
      kart_version: pr-120
    secrets: inherit
